--liquibase formatted sql

--changeset Admin:1.0
CREATE TABLE IF NOT EXISTS sensor
(
    id          SERIAL                      NOT NULL,
    sensor_name VARCHAR(50)                 NOT NULL,
    sensor_data INT4                        NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status      VARCHAR(50)                 NOT NULL,
    PRIMARY KEY (id)
) PARTITION BY HASH (id);

--changeset Admin:1.1
CREATE INDEX idx_sensor_status ON sensor (status);

--changeset Admin:1.2
CREATE TABLE IF NOT EXISTS SENSOR_HASH_PART_0_of_4 PARTITION OF SENSOR FOR VALUES WITH (MODULUS 4, REMAINDER 0);

--changeset Admin:1.3
CREATE TABLE IF NOT EXISTS SENSOR_HASH_PART_1_of_4 PARTITION OF SENSOR FOR VALUES WITH (MODULUS 4, REMAINDER 1);

--changeset Admin:1.4
CREATE TABLE IF NOT EXISTS SENSOR_HASH_PART_2_OF_4 PARTITION OF SENSOR FOR VALUES WITH (MODULUS 4, REMAINDER 2);

--changeset Admin:1.5
CREATE TABLE IF NOT EXISTS SENSOR_HASH_PART_3_OF_4 PARTITION OF SENSOR FOR VALUES WITH (MODULUS 4, REMAINDER 3);


