server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TimTsegelnik/ms-config.git
          refresh-rate: 10
  security:
    user:
      name: admin
      password: qwerty