server:
  port: 8084

spring:
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.type.mapping: "sensorData:com.example.auditservice.sensorDao.SensorData"
  liquibase:
    change-log: classpath:db/liquidbase/changelog-master.yml