version: "2"
services:

  sensor-listener:
    image: sensor-listener:latest
    restart: always
    expose:
      - '8088'
    depends_on:
      - kafka
      - zookeeper
      - sensor
      - sensor-listenr-db

  sensor-listenr-db:
    image: postgres:alpine3.13
    restart: always
    expose:
      - '5430'
    environment:
      POSTGRES_PASSWORD: qwerty

  sensor:
    image: sensor:latest
    restart: always

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    expose:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: on-failure
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka